baseurl = "https://nishantgandhi99.gitlab.io/"
title = "Nishant M Gandhi"
copyright = "\"Standing Tall, Seeing Far\""
canonifyurls = true
theme = "kiera"

paginate = 20

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Nishant M Gandhi"
    github = "nishantgandhi99"
    gitlab = ""
    linkedin = "nishantgandhi99"
    facebook = ""
    twitter = ""
    instagram = ""
    medium = "@nishantgandhi99"
    blogger = "nishantgandhi99"

[params]
    tagline = "Trying to Understand World by Reading Listening & Thinking."
